### ISSUE TITLE
Model Downloader

### ISSUE THREAD

**Issue by exdysa** [hiddenswitch/ComfyUI#17]
### Feature Idea

I like model downloader, but not what it downloads... What if there was a way to specify *alternate* downloadable models, maybe using a yaml file, a remote url containing a list, or some other means?

### Existing Solutions

Many nodes add one or two models, but rarely do they offer any control of what specific models or their source, and I can think of none which offer an entire menu of models.

### Other

:white_heart: hiddenswitch 4 eva

**Comment by doctorpangloss** [comment]
any node can add models to download using python. see https://github.com/AppMana/appmana-comfyui-nodes-extramodels/blob/e6b9319345599e0bc6960711f37565dc6372abe6/comfyui_extra_models/PixArt/nodes.py#L12 for an example.

since checkpoints are essentially executable, it was my opinion that the ones that can be downloaded should be specified in code. that said, a configuration file can create those UrlFile, HuggingFile and CivitFile objects that are already used by the fork to declare downloadable content

**Comment by exdysa** [comment]
> any node can add models to download using python. see https://github.com/AppMana/appmana-comfyui-nodes-extramodels/blob/e6b9319345599e0bc6960711f37565dc6372abe6/comfyui_extra_models/PixArt/nodes.py#L12 for an example.
> 
> since checkpoints are essentially executable, it was my opinion that the ones that can be downloaded should be specified in code. that said, a configuration file can create those UrlFile, HuggingFile and CivitFile objects that are already used by the fork to declare downloadable content

Thats fair. I think I understand your intention more now, and I like that it is meant to 'just work'. Our taste in models will always differ, but I appreciate that you let people start with something more than upstream & I plan on using HuggingFile() a lot regardless. I do wish it wasn't so hardcoded, but the fact that they are executable files does make it a reasonable exception.
